"""
📌 CONVERSATION HANDLER STATELARI
"""

# Test ishlash statelari
ANSWERING = 1
TEXT_ANSWER = 2
MATCHING_ANSWER = 3
ORDERING_ANSWER = 4

# Test yaratish statelari
UPLOAD_FILE = 10
SET_SUBJECT = 11
SET_DIFFICULTY = 12
SET_TIME_LIMIT = 13
SET_VISIBILITY = 14
SET_PASSING_SCORE = 15
SET_MAX_ATTEMPTS = 16
CONFIRM_TEST = 17
MANUAL_QUESTION = 18
MANUAL_OPTIONS = 19
MANUAL_CORRECT = 20
MANUAL_EXPLANATION = 21

# Ro'yxatdan o'tish statelari
REG_NAME = 30
REG_PHONE = 31
REG_ROLE = 32

# Admin statelari
ADMIN_ACTION = 40
ADMIN_BLOCK_USER = 41
ADMIN_DELETE_TEST = 42
ADMIN_BROADCAST = 43
